image: docker:latest

stages:
  - build
#  - deploy

variables:
  #CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  CONTAINER_IMAGE: codenetix/laravel-dms-proxy:$CI_BUILD_REF_NAME

before_script:
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE
  tags:
    - docker-build

#deploy_dev:
#  variables:
#    GIT_STRATEGY: none
#  stage: deploy
#  only:
#    - dev
#  script:
#    - docker run --env RANCHER_URL="http://rancher.codenetix.com/v1/projects/1a17584" --env RANCHER_ACCESS_KEY="$RANCHER_ACCESS_KEY" --env RANCHER_SECRET_KEY="$RANCHER_SECRET_KEY" --env RANCHER_STACK_ID="1st133" --env RANCHER_STACK_NAME="Default" --env RANCHER_SERVICE_NAME="proxy" mildberrydigital/rancher-remote-upgrade:latest proxy